name: Build PVE Kernel

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 时间 02:00 触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone Proxmox kernel repository
        run: |
          git clone https://git.proxmox.com/git/pve-kernel.git
          cd pve-kernel
          git submodule update --init --recursive

      - name: Check for 'bump version' commit
        id: check_commit
        run: |
          cd pve-kernel
          LATEST_COMMIT_MSG=$(git log -1 --pretty=%s)
          echo "LATEST_COMMIT_MSG=$LATEST_COMMIT_MSG" >> $GITHUB_ENV
          echo "latest_commit_message=$LATEST_COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Exit if no 'bump version' commit
        if: contains(steps.check_commit.outputs.latest_commit_message, 'bump version') == false
        run: |
          echo "No 'bump version' commit found. Exiting."
          exit 0

      - name: Set up Proxmox build container
        uses: docker://proxmox/pve-kernel-builder:latest

      - name: Build kernel
        run: |
          cd /pve-kernel
          make build-dir-fresh
          make deb

      - name: Create GitHub release
        id: create_release
        uses: ghcr.io/softprops/action-gh-release@v1
        with:
          files: |
            /pve-kernel/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload kernel packages as release assets
        run: |
          gh release upload ${{ steps.create_release.outputs.tag }} \
            /pve-kernel/*.deb \
            --clobber
