name: Build test

on:
  schedule:
    - cron: '0 18 * * *'  # 每天 中国时间 02:00 触发
  workflow_dispatch:

env:
  REPO_URL: https://git.proxmox.com/git/pve-kernel.git
  REPO_BRANCH: master
  CONFIG_FILE: .config
  SCRIPTS_PATH: ${{ github.workspace }}/scripts
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: true
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone source code
        run: git clone $REPO_URL -b $REPO_BRANCH pve-kernel
      
      - name: Fix ACS patch
        run: |
          cd pve-kernel
          sudo chmod a+x $SCRIPTS_PATH/ACS_patch.sh  && $SCRIPTS_PATH/ACS_patch.sh
      
      - name: Fix DEBUG_INFO_BTF
        run: |
          cd pve-kernel
          sed -i 's/${LINUX_TOOLS_DBG_DEB}/# ${LINUX_TOOLS_DBG_DEB}/' Makefile
          
      - name: Disable fwcheck
        run: |
          cd pve-kernel
          sed -i "s/rules fwcheck abicheck/rules abicheck/" debian/rules

      - name: Extract kernel version
        id: extract_version
        run: |
          cd pve-kernel
          KERNEL_VERSION=$(head -n1 debian/changelog | awk '{print $2}' | sed 's/[()]//g')
          echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV
          echo "kernel_version=$KERNEL_VERSION" >> $GITHUB_OUTPUT
          echo "Detected kernel version: $KERNEL_VERSION"


      - name: Extract changelog
        id: extract_changelog
        run: |
          cd pve-kernel
          # 提取变更内容（从第3行开始，直到空行），并替换 * 为 -（Markdown 列表）
          sed -n '3,/^$/p' debian/changelog | sed '/^$/d' | sed 's/^ *//g; s/^\*/-/' > changelog.txt
          
          # 提取 maintainer 时间信息（第一条 "-- ..."）
          maintainer_line=$(grep '^ -- ' debian/changelog | head -n1)
          
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat changelog.txt >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "$maintainer_line" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          cat changelog.txt
          echo "$maintainer_line"
